env_variables: 
  EMAILJS_SERVICE_ID: service_gjibnjc;
  EMAILJS_TEMPLATE_ID: template_v5hw2ym;
  EMAILJS_PUBLIC_KEY: c3wYcruUL-Jeg_u2d;
  MONGODB_URI: mongodb+srv://avramenko:1PnSF2W5nzHnVHoI@cluster0.fhahdj7.mongodb.net/;
  SECRET: GKXj2ai@P7@IX2v6Bl9kRiPg13iExrZ7@!Mwb128dX$%X3x!20